worker_processes auto;

events
{
    worker_connections 1024;
}

http
{
    default_type  application/octet-stream;

    sendfile      on;
    keepalive_timeout 65;

    server
    {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name _;

        #
        # ACME HTTP-01 challenge
        #
        location ^~ /.well-known/acme-challenge/
        {
            root /local/lego/acme;
            default_type text/plain;
            access_log off;
            log_not_found off;
            try_files $uri =404;
        }

        #
        # Everything else
        #
        location /
        {
            return 301 https://$host$request_uri;
        }
    }
}
