worker_processes auto;

pid /tmp/nginx.pid;

events
{
    worker_connections 8192;
    multi_accept on;
}

http
{
    default_type  application/octet-stream;

    access_log off;
    error_log  /dev/stderr notice;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;

    keepalive_timeout 65;
    server_tokens off;

    upstream whoami_backend
    {
        server whoami:80;

        keepalive 256;
        keepalive_requests 10000;
        keepalive_time 1h;
        keepalive_timeout 60s;
    }

    server
    {
        listen 80;
        listen 443 ssl;
        server_name _;
        http2 on;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        ssl_certificate     /run/secrets/nginx/tls.crt;
        ssl_certificate_key /run/secrets/nginx/tls.key;

        root /www;
        index index.html;

        proxy_intercept_errors on;
        error_page 502 503 504 /error_page_service_not_available.html;
        error_page 404 /error_page_not_found.html;

        location = /error_page_service_not_available.html
        {
            internal;
            default_type text/html;
            alias /cfg/error_page_service_not_available.html;
        }

        location = /error_page_not_found.html
        {
            internal;
            default_type text/html;
            alias /cfg/error_page_not_found.html;
        }

        location /whoami
        {
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_pass http://whoami_backend;

            proxy_set_header Host              $host;
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Info            routed-by-nginx-nrpc-proxy;
        }

        location /
        {
            try_files $uri $uri/ =404;
        }
    }
}
